# Generated by Django 4.1.7 on 2023-03-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snaraga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
                ('price1', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('price2', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/images/services/products')),
                ('description', models.TextField(max_length=550)),
            ],
        ),
    ]
