# Generated by Django 4.1.7 on 2023-03-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snaraga',
            name='type',
            field=models.CharField(choices=[('s', 'Спальники/палатки'), ('sn', 'Снаряжение'), ('p', 'прочее')], default=('p', 'прочее'), max_length=200),
        ),
    ]
