# Generated by Django 4.1.7 on 2023-03-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.CharField(max_length=335),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title_foto',
            field=models.ImageField(blank=True, height_field=180, null=True, upload_to='static/images/tour', width_field=270),
        ),
    ]
