# Generated by Django 4.1.7 on 2023-03-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_description_alter_tour_title_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='pro_gor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title_foto',
            field=models.ImageField(blank=True, default='http://placehold.it/460x460', null=True, upload_to='static/images/tour'),
        ),
        migrations.DeleteModel(
            name='Pro_goriki',
        ),
    ]
