# Generated by Django 4.1.7 on 2023-03-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_price_tour_priority_alter_tour_pro_gor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(choices=[('m', 'Иркутск, Иркутская область'), ('rf', 'Россия'), ('zg', 'Заграничный тур')], default=('m', 'Иркутск, Иркутская область'), max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('z', 'Зимний'), ('l', 'Летний'), ('v', 'Всесезонный'), ('e', 'Экскурсия')], default=('v', 'Всесезонный'), max_length=20),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
