# Generated by Django 4.1.7 on 2023-03-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_location_alter_tour_type_delete_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('Зимний', 'Зимний'), ('Летний', 'Летний'), ('Всесезонный', 'Всесезонный'), ('Экскурсия', 'Экскурсия')], default=('v', 'Всесезонный'), max_length=20),
        ),
    ]
