# Generated by Django 4.1.7 on 2023-03-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tour_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('foto', models.ImageField(blank=True, default='http://placehold.it/460x460', null=True, upload_to='static/images/excursions')),
                ('description', models.TextField()),
                ('priority', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('Зимний', 'Зимний'), ('Летний', 'Летний'), ('Всесезонный', 'Всесезонный')], default=('Всесезонный', 'Всесезонный'), max_length=20),
        ),
    ]
