# Generated by Django 4.1.7 on 2023-04-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('job', models.CharField(max_length=20)),
                ('title_foto_148x198', models.ImageField(blank=True, null=True, upload_to='static/images/about')),
                ('foto_100x134', models.ImageField(blank=True, null=True, upload_to='static/images/about')),
                ('vk', models.CharField(max_length=500)),
                ('skill_1', models.CharField(max_length=50)),
                ('skill_2', models.CharField(max_length=50)),
                ('skill_3', models.CharField(max_length=50)),
                ('skill_4', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
