# Generated by Django 4.1.7 on 2023-03-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('description', models.TextField(max_length=550)),
                ('title_foto', models.ImageField(blank=True, default='http://placehold.it/160x160', null=True, upload_to='static/images/shop/products')),
                ('detals', models.TextField()),
                ('priority', models.IntegerField(null=True)),
            ],
        ),
    ]
