# Generated by Django 4.1.7 on 2023-03-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('ts', 'Футболка'), ('sh', 'Шеврон'), ('t', 'Толстовка'), ('ot', 'Остальное')], default='ot', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
